### ISSUE TITLE
Add default values for fields

### ISSUE THREAD

**Issue by LordFckHelmchen** [EricWebsmith/pydantic_mermaid#3]
Currently, default values on fields are not rendered, e.g. for 
```Python
class A(BaseModel):
    a: int = 5
```

We'll get
```Mermaid
    class A {
        a: int
    }
```

Ideally we should get
```Mermaid
    class A {
        a: int = 5
    }
```

**Comment by EricWebsmith** [comment]
Thanks for the report. I believe this has been fix by v0.7.0 which is just released.
